### ISSUE TITLE
Import fields doesn't work

### ISSUE THREAD

**Issue by slaFFik** [slaFFik/BP-Groups-Extras#122]
by @kalico1:

> When I go to Extras tab >> All Fields, select one of my pre-sets and click on "Import" the fields are not added.

**Comment by slaFFik** [comment]
I will check.

**Comment by kalico1** [comment]
Hi @slaFFik I wonder if you have a timeline for this issue or #121 . This has completely broken our workflow, and we can't add new groups at all right now. If there's anything you can suggest to help us, it would be greatly appreciated :)

**Comment by kalico1** [comment]
I've done some further testing, and I suspect this is at least in part related to the theme. I reported the issue to ThemeIsle, and I'll let you know what I hear back.

**Comment by slaFFik** [comment]
@kalico1,
Great, thank you for letting me know.
Please keep me updated on this issue.

**Comment by kalico1** [comment]
Hi @slaFFik 
I have some new information to report. I am doing a massive plugin and theme conflict test across my entire network. Bug reporting turned on everywhere. I am still seeing a conflict with my theme; the theme dev, however, hasn't found a solution yet. 

At this point, I have mostly attributed the click/drag problem to CSS (see #121). Additionally, with all my plugins turned off except Bp and BPGE, the field "delete" buttons work correctly. 

The primary issue now is the inability to import groups of fields. 

When I try to import, I get popped up to the top of the page, and no import happens. It's like the # at the end of the URL is acting as an anchor tag, with nowhere to go. You can see this happening in the [screencast](https://screencast.com/t/lFWsHbkoNj1).

There are no errors in debug.log, but I have uncovered a console error. This error appears when no plugins are activated except BP and BPGE.
![arc_and_manage_group_ _colorado_community_college_system_ _nroc_community](https://cloud.githubusercontent.com/assets/7773902/26277405/84aa70a4-3d3b-11e7-84a5-63e8b1e35b1e.jpg)

I hope that might give you a clue as to what's going on here. 

Thanks,
Kalico

**Comment by kalico1** [comment]
I am pleased to report that we have discovered the root source of this issue, and it had nothing to do with anything I expected. 

I had unwittingly imported some code into my parent theme's header.php file, while attempting to fix a bunch of things that went wrong after the theme update.

I have an old script, from an old website, that we are trying to maintain on a new site (it's tricky) and it turns out that it calls the jquery-latest.min.js library, that's supposed to "keep jquery up to date".

It's an old and outdated library, and it is known to cause issues. 

Worse yet, my old script was calling it wrong: it's just linked directly in the header file, which is something that's not compliant with WP Codex (any JS libraries should be added using "wp-enqueue-script()" function). 

So now that I've dealt with that problem, everything in BPGE is working properly. Hurray!

Special thanks to the team at [WPMUDEV](http://premium.wpmudev.org) - it was Adam over there who helped me identify this problem and get it sorted out. 

This solves #121  as well!!

**Comment by slaFFik** [comment]
Awesome news! I'm glad you found the root cause.

I'm closing this and #122.
